version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: feature_flags_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/feature_flags_db
      JWT_SECRET: your-super-secret-jwt-key-here
    depends_on:
      - postgres
    command: sh -c "npx prisma db push && npm run dev"

  client:
    build: ./client
    ports:
      - "3030:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on:
      - server

volumes:
  postgres_data:
